import API_KEY from "../spotifyAPIkey"; 

const resSpotify = {
    "data": {
      "items": [
        {
          "track": {
            "album": {
              "album_type": "album",
              "artists": [
                {
                  "external_urls": {
                    "spotify": "https://open.spotify.com/artist/2pAWfrd7WFF3XhVt9GooDL"
                  },
                  "href": "https://api.spotify.com/v1/artists/2pAWfrd7WFF3XhVt9GooDL",
                  "id": "2pAWfrd7WFF3XhVt9GooDL",
                  "name": "MF DOOM",
                  "type": "artist",
                  "uri": "spotify:artist:2pAWfrd7WFF3XhVt9GooDL"
                }
              ],
              "available_markets": [
                "AD",
                "AE",
                "AG",
                "AL",
                "AM",
                "AO",
                "AR",
                "AT",
                "AU",
                "AZ",
                "BA",
                "BB",
                "BD",
                "BE",
                "BF",
                "BG",
                "BH",
                "BI",
                "BJ",
                "BN",
                "BO",
                "BR",
                "BS",
                "BT",
                "BW",
                "BY",
                "BZ",
                "CA",
                "CD",
                "CG",
                "CH",
                "CI",
                "CL",
                "CM",
                "CO",
                "CR",
                "CV",
                "CW",
                "CY",
                "CZ",
                "DE",
                "DJ",
                "DK",
                "DM",
                "DO",
                "DZ",
                "EC",
                "EE",
                "EG",
                "ES",
                "ET",
                "FI",
                "FJ",
                "FM",
                "FR",
                "GA",
                "GB",
                "GD",
                "GE",
                "GH",
                "GM",
                "GN",
                "GQ",
                "GR",
                "GT",
                "GW",
                "GY",
                "HK",
                "HN",
                "HR",
                "HT",
                "HU",
                "ID",
                "IE",
                "IL",
                "IN",
                "IQ",
                "IS",
                "IT",
                "JM",
                "JO",
                "JP",
                "KE",
                "KG",
                "KH",
                "KI",
                "KM",
                "KN",
                "KR",
                "KW",
                "KZ",
                "LA",
                "LB",
                "LC",
                "LI",
                "LK",
                "LR",
                "LS",
                "LT",
                "LU",
                "LV",
                "LY",
                "MA",
                "MC",
                "MD",
                "ME",
                "MG",
                "MH",
                "MK",
                "ML",
                "MN",
                "MO",
                "MR",
                "MT",
                "MU",
                "MV",
                "MW",
                "MX",
                "MY",
                "MZ",
                "NA",
                "NE",
                "NG",
                "NI",
                "NL",
                "NO",
                "NP",
                "NR",
                "NZ",
                "OM",
                "PA",
                "PE",
                "PG",
                "PH",
                "PK",
                "PL",
                "PS",
                "PT",
                "PW",
                "PY",
                "QA",
                "RO",
                "RS",
                "RW",
                "SA",
                "SB",
                "SC",
                "SE",
                "SG",
                "SI",
                "SK",
                "SL",
                "SM",
                "SN",
                "SR",
                "ST",
                "SV",
                "SZ",
                "TD",
                "TG",
                "TH",
                "TJ",
                "TL",
                "TN",
                "TO",
                "TR",
                "TT",
                "TV",
                "TW",
                "TZ",
                "UA",
                "UG",
                "US",
                "UY",
                "UZ",
                "VC",
                "VE",
                "VN",
                "VU",
                "WS",
                "XK",
                "ZA",
                "ZM",
                "ZW"
              ],
              "external_urls": {
                "spotify": "https://open.spotify.com/album/2XfBjZ0ZwKMfwYJDX0JR1O"
              },
              "href": "https://api.spotify.com/v1/albums/2XfBjZ0ZwKMfwYJDX0JR1O",
              "id": "2XfBjZ0ZwKMfwYJDX0JR1O",
              "images": [
                {
                  "height": 640,
                  "url": "https://i.scdn.co/image/ab67616d0000b27373fcd3730311f6ec3a4326dd",
                  "width": 640
                },
                {
                  "height": 300,
                  "url": "https://i.scdn.co/image/ab67616d00001e0273fcd3730311f6ec3a4326dd",
                  "width": 300
                },
                {
                  "height": 64,
                  "url": "https://i.scdn.co/image/ab67616d0000485173fcd3730311f6ec3a4326dd",
                  "width": 64
                }
              ],
              "name": "BORN LIKE THIS",
              "release_date": "2009-03-23",
              "release_date_precision": "day",
              "total_tracks": 21,
              "type": "album",
              "uri": "spotify:album:2XfBjZ0ZwKMfwYJDX0JR1O"
            },
            "artists": [
              {
                "external_urls": {
                  "spotify": "https://open.spotify.com/artist/2pAWfrd7WFF3XhVt9GooDL"
                },
                "href": "https://api.spotify.com/v1/artists/2pAWfrd7WFF3XhVt9GooDL",
                "id": "2pAWfrd7WFF3XhVt9GooDL",
                "name": "MF DOOM",
                "type": "artist",
                "uri": "spotify:artist:2pAWfrd7WFF3XhVt9GooDL"
              }
            ],
            "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BT",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CD",
              "CG",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "ET",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "GY",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IQ",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KI",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LI",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "LY",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MH",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MV",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NR",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PS",
              "PT",
              "PW",
              "PY",
              "QA",
              "RO",
              "RS",
              "RW",
              "SA",
              "SB",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "SR",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TJ",
              "TL",
              "TN",
              "TO",
              "TR",
              "TT",
              "TV",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VE",
              "VN",
              "VU",
              "WS",
              "XK",
              "ZA",
              "ZM",
              "ZW"
            ],
            "disc_number": 1,
            "duration_ms": 135066,
            "explicit": true,
            "external_ids": {
              "isrc": "GBMYF0900049"
            },
            "external_urls": {
              "spotify": "https://open.spotify.com/track/2Vy16OMt19FH30uQNTFdLk"
            },
            "href": "https://api.spotify.com/v1/tracks/2Vy16OMt19FH30uQNTFdLk",
            "id": "2Vy16OMt19FH30uQNTFdLk",
            "is_local": false,
            "name": "THAT'S THAT",
            "popularity": 63,
            "preview_url": "https://p.scdn.co/mp3-preview/2385cf12d1bea3df736f7d7ce3fc8ae87999f731?cid=774b29d4f13844c495f206cafdad9c86",
            "track_number": 14,
            "type": "track",
            "uri": "spotify:track:2Vy16OMt19FH30uQNTFdLk"
          },
          "played_at": "2022-12-21T17:23:29.382Z",
          "context": {
            "type": "playlist",
            "external_urls": {
              "spotify": "https://open.spotify.com/playlist/37i9dQZF1F0sijgNaJdgit"
            },
            "href": "https://api.spotify.com/v1/playlists/37i9dQZF1F0sijgNaJdgit",
            "uri": "spotify:playlist:37i9dQZF1F0sijgNaJdgit"
          }
        }
      ],
      "next": "https://api.spotify.com/v1/me/player/recently-played?before=1671643409382&limit=1",
      "cursors": {
        "after": "1671643409382",
        "before": "1671643409382"
      },
      "limit": 1,
      "href": "https://api.spotify.com/v1/me/player/recently-played?limit=1"
    },
    "status": 200,
    "statusText": "OK",
    "headers": {
      "cache-control": "private, max-age=0",
      "content-length": "1387",
      "content-type": "application/json; charset=UTF-8"
    },
    "config": {
      "transitional": {
        "silentJSONParsing": true,
        "forcedJSONParsing": true,
        "clarifyTimeoutError": false
      },
      "adapter": [
        "xhr",
        "http"
      ],
      "transformRequest": [
        null
      ],
      "transformResponse": [
        null
      ],
      "timeout": 0,
      "xsrfCookieName": "XSRF-TOKEN",
      "xsrfHeaderName": "X-XSRF-TOKEN",
      "maxContentLength": -1,
      "maxBodyLength": -1,
      "env": {},
      "headers": {
        "Accept": "application/json",
        "Content-Type": null,
        "Authorization": API_KEY
      },
      "params": {
        "limit": "1"
      },
      "method": "get",
      "url": "https://api.spotify.com/v1/me/player/recently-played"
    },
    "request": {}
  }

  export default resSpotify;